version: "3.8"

services:
  broker:
    image: python:3.8-slim
    container_name: broker
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "sed -i 's/HOST = \"broker\"/HOST = \"0.0.0.0\"/g' broker.py && python -u broker.py"
    ports:
      - "5000:5000"
    networks:
      mynetwork:
        ipv4_address: 172.28.0.2

  producer1:
    image: python:3.8-slim
    container_name: producer1
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - broker
    command: bash -c "sed -i 's/HOST = \"127.0.0.1\"/HOST = \"broker\"/g' producer.py && python -u producer.py"
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 172.28.0.3

  producer2:
    image: python:3.8-slim
    container_name: producer2
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - broker
    command: bash -c "sed -i 's/HOST = \"127.0.0.1\"/HOST = \"broker\"/g' producer.py && python -u producer.py"
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 172.28.0.4

  producer3:
    image: python:3.8-slim
    container_name: producer3
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - broker
    command: bash -c "sed -i 's/HOST = \"127.0.0.1\"/HOST = \"broker\"/g' producer.py && python -u producer.py"
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 172.28.0.5

  producer4:
    image: python:3.8-slim
    container_name: producer4
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - broker
    command: bash -c "sed -i 's/HOST = \"127.0.0.1\"/HOST = \"broker\"/g' producer.py && python -u producer.py"
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 172.28.0.6

  consumer1:
    image: python:3.8-slim
    container_name: consumer1
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - broker
    command: bash -c "sed -i 's/HOST = \"127.0.0.1\"/HOST = \"broker\"/g' consumer.py && python -u consumer.py"
    networks:
      mynetwork:
        ipv4_address: 172.28.0.7

  consumer2:
    image: python:3.8-slim
    container_name: consumer2
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - broker
    command: bash -c "sed -i 's/HOST = \"127.0.0.1\"/HOST = \"broker\"/g' consumer.py && python -u consumer.py"
    networks:
      mynetwork:
        ipv4_address: 172.28.0.8

  consumer3:
    image: python:3.8-slim
    container_name: consumer3
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - broker
    command: bash -c "sed -i 's/HOST = \"127.0.0.1\"/HOST = \"broker\"/g' consumer.py && python -u consumer.py"
    networks:
      mynetwork:
        ipv4_address: 172.28.0.9

  consumer4:
    image: python:3.8-slim
    container_name: consumer4
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - broker
    command: bash -c "sed -i 's/HOST = \"127.0.0.1\"/HOST = \"broker\"/g' consumer.py && python -u consumer.py"
    networks:
      mynetwork:
        ipv4_address: 172.28.0.10

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16"